import {
  FaReact,
  FaNodeJs,
  FaDatabase,
  FaJs,
  FaAws,
  FaDocker,
  FaGitAlt,
  FaServer,
} from "react-icons/fa";
import { SiJira } from "react-icons/si";

const certificationsData = [
  {
    id: 1,
    title: "HTML5, CSS3 & Bootstrap | Udemy",
    desc: "Semantic HTML5 markup. Responsive design with Bootstrap grid system. Flexbox utilities. Accessibility standards. Cross-browser compatibility.",
    pdf: "#",
    months: 3,
    icon: <FaJs />,
  },
  {
    id: 2,
    title: "JavaScript (ES6+) | Udemy",
    desc: "Modern ES6+ syntax. Asynchronous programming. DOM manipulation. Functional programming concepts. Browser APIs.",
    pdf: "#",
    months: 2.5,
    icon: <FaJs />,
  },
  {
    id: 3,
    title: "Node.js Backend Development | Udemy",
    desc: "Event-driven architecture. RESTful APIs. Authentication & authorization. Middleware patterns. Error handling.",
    pdf: "#",
    months: 2.5,
    icon: <FaNodeJs />,
  },
  {
    id: 4,
    title: "React.js Ecosystem | Udemy",
    desc: "Component-driven architecture. React Hooks. Context API. State management. Performance optimization techniques.",
    pdf: "#",
    months: 2.5,
    icon: <FaReact />,
  },
  {
    id: 5,
    title: "Next.js Framework | Udemy",
    desc: "App Router. Server-side rendering (SSR). Static site generation (SSG). API routes. Middleware and performance optimization.",
    pdf: "#",
    months: 2,
    icon: <FaReact />,
  },
  {
    id: 6,
    title: "TypeScript Development | Udemy",
    desc: "Static typing. Interfaces and generics. Advanced types. Scalable application design. React and Node.js integration.",
    pdf: "#",
    months: 2,
    icon: <FaJs />,
  },
  {
    id: 7,
    title: "Jira & Agile Project Management | Udemy",
    desc: "Agile and Scrum workflows. Sprint planning. Issue and backlog management. Kanban boards. Team collaboration and reporting.",
    pdf: "#",
    months: 1,
    icon: <SiJira />,
  },
  {
    id: 8,
    title: "PostgreSQL Database | Udemy",
    desc: "Relational data modeling. Complex SQL queries. Performance tuning. ACID properties. ORM integration.",
    pdf: "#",
    months: 2,
    icon: <FaDatabase />,
  },
  {
    id: 9,
    title: "GraphQL API Development | Udemy",
    desc: "Schema design. Resolver implementation. Apollo Server & Client. Performance optimization. Real-time data handling.",
    pdf: "#",
    months: 2,
    icon: <FaServer />,
  },
  {
    id: 10,
    title: "Testing (Unit, Integration & E2E) | Udemy",
    desc: "Jest framework. React Testing Library. Cypress E2E testing. Mocking strategies. CI/CD test automation.",
    pdf: "#",
    months: 2,
    icon: <FaJs />,
  },
  {
    id: 11,
    title: "Docker & Containerization | Udemy",
    desc: "Docker images and containers. Docker Compose. Multi-stage builds. Environment isolation. Deployment workflows.",
    pdf: "#",
    months: 2,
    icon: <FaDocker />,
  },
  {
    id: 12,
    title: "Cloud Deployment & CI/CD | Udemy",
    desc: "AWS & Vercel deployments. GitHub Actions. CI/CD pipelines. Monitoring and scalability strategies.",
    pdf: "#",
    months: 2.5,
    icon: <FaAws />,
  },
  {
    id: 13,
    title: "Git & Collaboration Tools | Udemy",
    desc: "Version control fundamentals. Branching strategies. Pull requests. Code reviews. Team collaboration workflows.",
    pdf: "#",
    months: 1.5,
    icon: <FaGitAlt />,
  },
  {
    id: 14,
    title: "Git & Collaboration Tools | Udemy",
    desc: "Version control fundamentals. Branching strategies. Pull requests. Code reviews. Team collaboration workflows.",
    pdf: "#",
    months: 1.5,
    icon: <FaGitAlt />,
  },
];

export default certificationsData;
