import {
  FaReact,
  FaNodeJs,
  FaDatabase,
  FaJs,
  FaAws,
  FaDocker,
  FaGitAlt,
  FaServer,
} from "react-icons/fa";
import { SiPostman } from "react-icons/si";

const certificationsData = [
  {
    id: 1,
    title: "HTML5, CSS3 & Bootstrap Certification",
    desc: "Built semantic layouts and responsive interfaces using Bootstrap grid system. Applied accessibility standards and ensured cross-browser compatibility.",
    pdf: "#",
    months: "2-3",
    icon: <FaJs />,
  },
  {
    id: 2,
    title: "JavaScript (ES6+) Certification",
    desc: "Mastered modern JavaScript syntax, asynchronous programming, and DOM manipulation. Optimized performance and handled browser APIs effectively.",
    pdf: "#",
    months: "2-3",
    icon: <FaJs />,
  },
  {
    id: 3,
    title: "Node.js Backend Development Certification",
    desc: "Developed RESTful APIs with structured architecture. Implemented authentication, middleware patterns, and efficient error handling.",
    pdf: "#",
    months: "2-3",
    icon: <FaNodeJs />,
  },
  {
    id: 4,
    title: "React.js Development Certification",
    desc: "Built scalable component-based applications using Hooks and Context API. Optimized rendering performance and reusable UI structures.",
    pdf: "#",
    months: "2-3",
    icon: <FaReact />,
  },
  {
    id: 5,
    title: "Next.js Framework Certification",
    desc: "Implemented SSR and SSG with App Router architecture. Built optimized API routes and improved application performance.",
    pdf: "#",
    months: "2-3",
    icon: <FaReact />,
  },
  {
    id: 6,
    title: "TypeScript Development Certification",
    desc: "Applied static typing, interfaces, and generics in scalable applications. Integrated TypeScript with frontend and backend systems.",
    pdf: "#",
    months: "2-3",
    icon: <FaJs />,
  },
  {
    id: 7,
    title: "PostgreSQL Database Certification",
    desc: "Designed relational schemas and optimized SQL queries. Ensured data integrity and performance through indexing strategies.",
    pdf: "#",
    months: "2-3",
    icon: <FaDatabase />,
  },
  {
    id: 8,
    title: "GraphQL API Development Certification",
    desc: "Designed schemas and resolvers for efficient data fetching. Implemented optimized API communication with modern backend systems.",
    pdf: "#",
    months: "2-3",
    icon: <FaServer />,
  },
  {
    id: 9,
    title: "Jest Testing Certification",
    desc: "Implemented unit and integration testing strategies. Applied mocking techniques and maintained strong test coverage.",
    pdf: "#",
    months: "2-3",
    icon: <FaJs />,
  },
  {
    id: 10,
    title: "Cypress End-to-End Testing Certification",
    desc: "Built automated E2E testing workflows. Validated user interaction scenarios and integrated testing into CI/CD pipelines.",
    pdf: "#",
    months: "2-3",
    icon: <FaJs />,
  },
  {
    id: 11,
    title: "Postman API Testing Certification",
    desc: "Tested REST APIs using collections and environments. Automated request validation and documented backend services.",
    pdf: "#",
    months: "2-3",
    icon: <SiPostman />,
  },
  {
    id: 12,
    title: "Docker & Containerization Certification",
    desc: "Created containerized applications using Docker and Compose. Managed multi-stage builds and environment isolation.",
    pdf: "#",
    months: "2-3",
    icon: <FaDocker />,
  },
  {
    id: 13,
    title: "Cloud Deployment & CI/CD Certification",
    desc: "Deployed applications on cloud platforms. Configured automated CI/CD pipelines and monitored scalable infrastructure.",
    pdf: "#",
    months: "2-3",
    icon: <FaAws />,
  },
  {
    id: 14,
    title: "Git & Version Control Certification",
    desc: "Applied branching strategies and collaborative workflows. Managed pull requests, reviews, and structured version control practices.",
    pdf: "#",
    months: "2-3",
    icon: <FaGitAlt />,
  },
];

export default certificationsData;
